### ISSUE TITLE
Need additional Properties in studentattendanceByClass

### ISSUE THREAD

**Issue by kumaresan-subramani** [Klartopedia/erp-api#383]
![image](https://github.com/Klartopedia/erp-api/assets/36756050/26a690af-1599-4b1a-a90c-a25c6444f1b0)

## endpoint - studentattendanceByClass

in above endpoint need 3 additional properties baed on student

- nof.of.days.absent
- no.of.days.present
- total.attendeance percent

**Comment by ArunprasadRajendran** [comment]
dropped
